version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web_backend:
    build:
      context: .
      dockerfile: ./Dockerfile1
    command: ./setup.sh
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  web_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile2
    command: ./setup2.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db


